name: factually

services:
  extraction-service:
    build: ./extraction-service
    environment:
      - STORAGE_SERVICE_URL=http://storage-service:8000
    ports:
      - "8000:8000"
    networks:
      - factually-network
    depends_on:
      - storage-service

  storage-service:
    build: ./storage-service
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo_user:mongo_pass@mongodb:27017/factually_db
    networks:
      - factually-network
    ports:
      - "8001:8000"
    depends_on:
      - mongodb

  mongodb: 
    image: mongo:5.0-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    networks:
      - factually-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init/init_mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command: mongod --quiet --logpath /dev/null

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - factually-network

volumes:
  mongodb_data:
  ollama_data:

networks:
  factually-network:
    driver: bridge