name: factually

services:
  extraction-service:
    build: ./extraction-service
    environment:
      - STORAGE_SERVICE_URL=http://storage-service:8000
    ports:
      - "8000:8000"
    networks:
      - factually-network
    depends_on:
      - storage-service

  storage-service:
    build: ./storage-service
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo_user:mongo_pass@mongodb:27017/factually_db
      - WEAVIATE_HOST=weaviate
      - WEAVIATE_PORT=8080
      - WEAVIATE_GRPC=50051
      - OLLAMA_CONNECTION_STRING=http://ollama:11434
    networks:
      - factually-network
    ports:
      - "8001:8000"
    depends_on:
      - mongodb

  mongodb: 
    image: mongo:5.0-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    networks:
      - factually-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init/init_mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    command: mongod --quiet --logpath /dev/null

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - factually-network

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - factually-network

  rabbitmq:
    image: rabbitmq:4.0.6-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - factually-network

volumes:
  mongodb_data:
  ollama_data:
  weaviate_data:

networks:
  factually-network:
    driver: bridge